name: ct_analysis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - openpyxl
  - jupyterlab
  - ipykernel
  - joblib
  - pip
  - pip:
      - notebook
